export const GET_PRODUCTS_SUCCESS = "GET PRODUCT SUCCESSFULL";
export const GET_PRODUCTS_FAILED = "GET PRODUCT FAILED"
export const GET_PRODUCT_BY_ID_REQUESTED = "GET PRODUCT BY ID REQUESTED"
export const GET_PRODUCT_BY_ID_SUCCESSFULL = "GET PRODUCT BY ID SUCCESSFULL"
export const GET_PRODUCT_BY_ID_FAILED = "GET PRODUCT BY ID FAILED"
export const GET_PRODUCT_BY_ID_RESET = "GET PRODUCT BY ID RESET"